blank_issues_enabled: false
contact_links:
  - name: Sigma Discord Support
    url: https://discord.gg/5t3KaGX8Bx
    about: I am part of Sigma! The makers of the original egg. Contact me in there for support!
