name: Request PHP packages
description: Request a version of the Pterodactyl Nginx egg with new packages of your choice!
title: "[Request]: "
labels: ["request"]
assignees:
  - JohnB17
body:
  - type: markdown
    attributes:
      value: |
        These should only be used to request packages!
  - type: textarea
    id: packages
    attributes:
      label: Packages
      description: What PHP packages do you want added?
      placeholder: php8-simplexml php8-...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platforms
      description: What platforms do you want the egg for?
      options:
        - Both
        - AMD64
        - Arm64
    validations:
      required: true
    placeholder: Both
  - type: checkboxes
    id: license
    attributes:
      label: License
      description: By submitting this issue, you agree to abide by our MIT License
      options:
        - label: I agree to abide by the MIT License in this Repository
          required: true
